# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170313_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.TextField(default='No category'),
        ),
    ]
