# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170327_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='rate',
        ),
    ]
