# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20170327_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment1',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment1',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment1',
        ),
    ]
