# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20170327_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
